.TH TXT2IMG 1 "May 2026" "txt2img 1.0.0" "User Commands"
.SH NAME
txt2img \- Render wrapped text into an image
.SH SYNOPSIS
.B txt2img
[\fIOPTIONS\fR] \fIIMAGE_FILE\fR
.SH DESCRIPTION
txt2img is a cross-platform command-line utility designed for rendering wrapped text into images.
It supports ANSI styles, word wrapping, and multi-page output.
.SH OPTIONS
.TP
\fB\-h, \-\-help\fR
Show help message
.TP
\fB\-v, \-\-version\fR
Show version information
.TP
\fB\-W, \-\-width\fR \fIWIDTH\fR
Specify the width for wrapping
.TP
\fB\-n, \-\-output\fR \fIFILE\fR
Specify the output filename
.SH AUTHOR
Ian Pride <faithnomoread@yahoo.com>
.SH SEE ALSO
https://github.com/Lateralus138/txt2img
